# Generated by Django 5.1 on 2024-10-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, null=True)),
                ('benefit_name', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('period', models.TextField(blank=True, null=True)),
                ('age_rating', models.TextField(blank=True, db_column='age rating', null=True)),
                ('ticket_price', models.TextField(blank=True, db_column='Ticket Price', null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'play',
                'managed': False,
            },
        ),
    ]
